; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "medical store"
#define MyAppVersion "1.5.1"
#define MyAppPublisher "AAI,Inc"
#define MyAppExeName "MyProg-x64.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{DE595D5D-73DB-4174-9560-E43B9CAC13D9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputBaseFilename=mysetup
SetupIconFile=C:\Users\User\Desktop\veterinarystore\medical store.ico
Password=Ahadsaab@263
Encryption=yes
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\BouncyCastle.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\BouncyCastle.Cryptography.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\FontAwesome.Sharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Google.Protobuf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Google.Protobuf.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Google.Protobuf.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\K4os.Compression.LZ4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\K4os.Compression.LZ4.Streams.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\K4os.Compression.LZ4.Streams.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\K4os.Compression.LZ4.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\K4os.Hash.xxHash.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\K4os.Hash.xxHash.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\libgcc_s_dw2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MedicineShop.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MedicineShop.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MedicineShop.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Microsoft.Bcl.AsyncInterfaces.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Microsoft.Extensions.DependencyInjection.Abstractions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Microsoft.Extensions.DependencyInjection.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MongoDB.Bson.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MongoDB.Bson.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MySql.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\MySql.Data.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Newtonsoft.Json.Bson.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Newtonsoft.Json.Bson.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Newtonsoft.Json.Bson.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\Newtonsoft.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\qpdf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\QuestPDF.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\QuestPDF.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\QuestPdfSkia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Configuration.ConfigurationManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Configuration.ConfigurationManager.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Diagnostics.DiagnosticSource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Diagnostics.DiagnosticSource.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.IO.Pipelines.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.IO.Pipelines.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\System.Threading.Tasks.Extensions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\User\Desktop\veterinarystore\MedicineShop\bin\Release\ZstdSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

